---
docker_directory: /opt/docker
mc_discord_bot_auth_token: "{{ lookup('bitwarden.secrets.lookup', '4bab3e2c-352b-497b-a872-b3c20164e432') }}"
mc_discord_bot_channel_id: "{{ lookup('bitwarden.secrets.lookup', '86123af4-57a2-4589-824b-b3c20165f06a') }}"
mc_discord_invite_link: "{{ lookup('bitwarden.secrets.lookup', '2acb4968-6ddd-4c7a-a33b-b3c2017e5e97') }}"
mc_rcon_password: "{{ lookup('bitwarden.secrets.lookup', '364dbb04-8dbd-49c8-afc1-b3c10186fb40') }}"
mc_velocity_proxy_forwarding_secret: "{{ lookup('bitwarden.secrets.lookup', '4c6b2fc4-f7ad-4ad8-998e-b3c00038403a') }}"
mc_whitelist_json: "{{ lookup('bitwarden.secrets.lookup', '5f65bbe5-894a-4090-bc47-b3c10095964b') }}"
