---
- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"
  become: true

- name: Disable empty password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Disable remote root login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart sshd

- name: Ensure docker daemon settings are configured
  ansible.builtin.copy:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: restart docker
