---
- name: Add Docker apt repository key
  ansible.builtin.get_url:
    url: "{{ docker_repo_key_url }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ cpu_arch }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] {{ docker_repo_url }} {{ ansible_facts['distribution_release'] }} stable"
    state: present

- name: Add gVisor apt repository key
  ansible.builtin.get_url:
    url: "{{ gvisor_repo_key_url }}"
    dest: /etc/apt/trusted.gpg.d/gvisor.asc
    mode: '0644'
    force: true

- name: Add gVisor apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ cpu_arch }} signed-by=/etc/apt/trusted.gpg.d/gvisor.asc] {{ gvisor_repo_url }} release main"
    state: present

- name: Ensure Docker is installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - runsc
    state: present
    update_cache: true
