---
- name: Ensure docker daemon settings are configured
  ansible.builtin.copy:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: "Restart Docker service"

- name: Ensure {{ docker_directory }} exists
  ansible.builtin.file:
    path: "{{ docker_directory }}"
    state: directory
    mode: '0755'
  become: true

- name: Copy service files to {{ docker_directory }}
  ansible.builtin.copy:
    src: "./files/docker/."
    dest: "{{ docker_directory }}"
    mode: "0644"
    owner: root
    group: root
    remote_src: no
  become: true

- name: Create docker network
  ansible.builtin.command: docker network create proxy-network
  failed_when: false
  become: true

- name: Launch caddy
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ docker_directory }}/caddy"
  become: true

- name: Launch mc-proxy service
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ docker_directory }}/mc-proxy"
  environment:
    MCPROXY_VELOCITY_FORWARDING_SECRET: "{{ mcproxy_velocity_forwarding_secret }}"
  become_flags: '-E' # preserve env vars
  become: true

- name: Launch uptime-kuma
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ docker_directory }}/uptime-kuma"
  become: true
